GET http://localhost:8080/topjava/rest/meals/
Accept: application/json

###

GET http://localhost:8080/topjava/rest/meals/filter?startDate=2020-01-30&startTime=00:00:00&endDate=2020-01-30&endTime=23:59:59
Accept: application/json

###

GET http://localhost:8080/topjava/rest/meals/100008
Accept: application/json

###

### !!! An empty line needs to separate the request header from the actual
POST http://localhost:8080/topjava/rest/meals
Content-Type: application/json

{"id":null,"dateTime":"2020-02-15T20:00:00","description":"RestУжин","calories":510,"user":null}
###

GET http://localhost:8080/topjava/rest/meals/100011
Accept: application/json

###

PUT http://localhost:8080/topjava/rest/meals/100011
Content-Type: application/json

{"id":100011,"dateTime":"2020-02-15T20:00:00","description":"UpdateRestУжин","calories":510,"user":null}
###

GET http://localhost:8080/topjava/rest/meals/100011
Accept: application/json

###

DELETE http://localhost:8080/topjava/rest/meals/100011
Accept: application/json

###